#.travis.yml

language: node_js
node_js:
  - stable # Download the stable node version

branches:
  only:
    - master

# before_script:
#   - npm i -g @angular/cli
#   - npm i -g angular-cli-ghpages

script:
  - ng build --prod --base-href='https://jackkarichkovskiy.github.io/ess-game/'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local_dir: dist # Only copy the dist conents
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change